#pragma once

// SwitchCast owns its version, IPC protocol, Atmosphere content ID, and
// configuration namespace. It does not register or depend on SysDVR.
#define SWITCHCAST_VERSION_STRING "0.4.0"
#define SWITCHCAST_IPC_VERSION 4
#define SWITCHCAST_CRASH_MODULEID 0x6A
#define SWITCHCAST_CONTENT_ID 0x00FF000053434153

#define ERR_IPC_INVHEADER \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 9)
#define ERR_IPC_INVSIZE \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 10)
#define ERR_IPC_INVMAGIC \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 11)
#define ERR_IPC_UNKCMD \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 13)
#define ERR_MAIN_NOTRUNNING \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 18)
#define ERR_INIT_FAILED \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 21)
#define ERR_MAIN_ALLOC_DISABLED \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 24)
#define ERR_SWITCHCAST_VIDEO \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 25)
#define ERR_SWITCHCAST_TRANSPORT \
	MAKERESULT(SWITCHCAST_CRASH_MODULEID, 26)

#define ERR_HIPC_UNKREQ MAKERESULT(11, 403)

// Transport values shared by the sysmodule and Settings UI.
#define TYPE_MODE_INVALID 0
#define TYPE_MODE_CAST 1
#define TYPE_MODE_USB_DOCK 2
#define TYPE_MODE_NULL 3

#define CMD_ENABLE 1
#define CMD_DISABLE 2
#define CMD_SET_BLANK_SCREEN 3
#define CMD_SET_TRANSPORT 4
#define CMD_GET_VER 100
#define CMD_GET_ENABLED 101
#define CMD_DEBUG_CRASH 102
#define CMD_GET_CAST_STATUS 104
#define CMD_GET_CAST_TARGET_DELAY 105
#define CMD_GET_CAST_RECEIVER_DELAY 106
#define CMD_GET_BLANK_SCREEN 107
#define CMD_GET_TRANSPORT 108

// SwitchCast connection diagnostics exposed to the Settings application.
#define CAST_STATUS_OFF 0
#define CAST_STATUS_DISCOVERING 1
#define CAST_STATUS_CONNECTING 2
#define CAST_STATUS_NEGOTIATING 3
#define CAST_STATUS_UDP_READY 4
#define CAST_STATUS_STREAMING 5
#define CAST_STATUS_ANSWER_REJECTED 6
#define CAST_STATUS_ANSWER_TIMEOUT 7
#define CAST_STATUS_NETWORK_ERROR 8
#define CAST_STATUS_PACKET_ERROR 9
#define CAST_STATUS_WAITING_GAME 10
#define CAST_STATUS_GAME_MONITOR_ERROR 11
#define CAST_STATUS_MEMORY_ERROR 12
#define CAST_STATUS_CODEC_TIMEOUT 13
#define CAST_STATUS_RECEIVER_CLOSED 14
#define CAST_STATUS_CONTROL_ERROR 15
#define CAST_STATUS_OFFER_ERROR 16
#define CAST_STATUS_RESERVED 17
#define CAST_STATUS_CONTROL_SEND_ERROR 18
#define CAST_STATUS_CONTROL_POLL_ERROR 19
#define CAST_STATUS_CONTROL_HEADER_ERROR 20
#define CAST_STATUS_CONTROL_FRAME_TOO_LARGE 21
#define CAST_STATUS_CONTROL_BODY_ERROR 22
#define CAST_STATUS_CONTROL_DECODE_ERROR 23
#define CAST_STATUS_CONTROL_ENCODE_ERROR 24
#define CAST_STATUS_CONTROL_PENDING_ERROR 25
#define CAST_STATUS_CONTROL_SOCKET_POLL_ERROR 26
#define CAST_STATUS_CONTROL_SOCKET_CLOSED 27
#define CAST_STATUS_RECEIVER_STATUS_TIMEOUT 28
#define CAST_STATUS_RESERVED_29 29
#define CAST_STATUS_RECOVERING 30
#define CAST_STATUS_RESERVED_31 31

// Compatibility aliases for status names used by the current receiver UI.
#define CAST_STATUS_WAITING_HTTP CAST_STATUS_NEGOTIATING
#define CAST_STATUS_HTTP_CONNECTED CAST_STATUS_UDP_READY
#define CAST_STATUS_LOAD_FAILED CAST_STATUS_ANSWER_REJECTED
#define CAST_STATUS_HTTP_TIMEOUT CAST_STATUS_ANSWER_TIMEOUT
#define CAST_STATUS_HLS_ERROR CAST_STATUS_PACKET_ERROR
#define CAST_STATUS_HLS_STARTUP_TIMEOUT CAST_STATUS_CODEC_TIMEOUT
#define CAST_STATUS_HTTP_REQUEST_ERROR CAST_STATUS_OFFER_ERROR
#define CAST_STATUS_PREPARING_HLS CAST_STATUS_RESERVED
#define CAST_STATUS_APP_ID_MISSING CAST_STATUS_RESERVED_29
#define CAST_STATUS_RECEIVER_READY_TIMEOUT CAST_STATUS_RECOVERING
#define CAST_STATUS_RECEIVER_STREAM_ERROR CAST_STATUS_RESERVED_31
#define CAST_STATUS_MIRROR_STARTUP_TIMEOUT CAST_STATUS_CODEC_TIMEOUT
#define CAST_STATUS_MEDIA_ERROR_FLAG 0x80000000U
#define CAST_STATUS_MEDIA_ERROR_CODE_MASK 0x7FFFFFFFU

// USB Dock connection states occupy a separate range from Cast diagnostics.
#define USB_STATUS_OFF 32
#define USB_STATUS_INITIALIZING 33
#define USB_STATUS_WAITING_DOCK 34
#define USB_STATUS_WAITING_GAME 35
#define USB_STATUS_STREAMING 36
#define USB_STATUS_INIT_ERROR 37
#define USB_STATUS_IO_ERROR 38
#define USB_STATUS_CAPTURE_ERROR 39
